repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
      - id: go-mod-tidy-repo
      - id: go-vet-mod
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.61.0
    hooks:
      - id: golangci-lint
